#theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman
title: Aastha Mehta
page.title: Aastha Mehta
tagline: Tenure-Track Assistant Professor @UBC CS
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aasthakm.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass
